# Generated by Django 4.1.7 on 2023-04-20 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stockUnidades', models.PositiveIntegerField()),
                ('stockGramos', models.FloatField(default=0)),
                ('precio', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadSolicitada', models.PositiveIntegerField()),
                ('productos', models.ManyToManyField(to='produccion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('productoOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.productoorden')),
            ],
        ),
    ]
