# Generated by Django 4.1.7 on 2023-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='productoOrden',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='productoOrden',
            field=models.ManyToManyField(to='produccion.productoorden'),
        ),
    ]
