# Generated by Django 4.1.7 on 2023-04-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_remove_ordenproduccion_productoorden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stockUnidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
