# Generated by Django 4.1.7 on 2023-04-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_productoorden_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoorden',
            old_name='productos',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
