# Generated by Django 4.1.7 on 2023-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_remove_productoorden_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='ordenCompletada',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
