# Generated by Django 4.1.7 on 2023-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_productoorden_cantidadproducida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='ordenDespacho',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
